# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# Enables configuration caching for faster subsequent builds.
org.gradle.configuration-cache=true

# AndroidX package structure
android.useAndroidX=true

# Suppress dependency constraints warning
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
