steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--timeout'
    - '300s'
    - '--min-instances'
    - '1'
    - '--update-env-vars'
    - 'CANVA_CLIENT_ID=${_CANVA_CLIENT_ID}'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/511453050214-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: pastoral-care-for-pco
  _REGION: us-central1
  _CANVA_CLIENT_ID: 'OC-AZ9dHwB8GH1_'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
